server:
  port: 8080

# Jaeger
opentracing:
  jaeger:
    enabled: true
    udp-sender.host: 127.0.0.1
    udp-sender.port: 6831

# Cassandra
spring:
  application:
    name: rdk-binance-module
  data:
    cassandra:
      keyspace-name: rkd_binance_module
      contact-points: 127.0.0.1
      port: 9042

# Kafka
  kafka:
    bootstrap-servers: localhost:9092

# Binance
binance:
  url:
    spot: https://api.binance.com
    future: https://fapi.binance.com
  wallet:
    standard-fiat-coin: BRL
    standard-stable-coin: USDT
  market:
    minimum-fiat-coin: 100
    minimum-stable-coin: 20

# Micrometer
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  endpoint:
    prometheus:
      enabled: true

micrometer:
  export:
    prometheus:
      enabled: true

# Strategies
module:
  spot:
    status: true
    frequency: 555000
    vector: UP
    minimum-range: 0.0
    maximum-range: 0.0
    rank: 3
    stop-limit: 0.5
    target-price: 2.5
    strategy: '{
      two_ma: true
    }'
  future:
    status: false
    frequency: 5000
    vector: DOWN
    minimum-range: 0.3
    maximum-range: 0.4
    rank: 0
    stop-limit: 0.5
    target-price: 2.5
    strategy: '{
      two_ma: false
    }'

